// package exceptions;

// public class FinallyKeyword {
//     public static void main(String[] args) {
//         try{
//              System.out.println("inside try block");
//             int l=5/0;
           
//         }
//         catch(Exception e){
//             System.out.println("inside catch..");
//         }
//         catch(NullPointerException e){
//             System.out.println(e);
//         }
//         finally{
//             System.out.println("finally block..");
//         }

//         System.out.println("try catch finally completed");
//     }
// }
